
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"    # HTTP
      - "443:443"  # HTTPS
    volumes:
      - /home/ec2-user/ssl-gg:/etc/nginx/ssl:ro
      - ./nginx-staging.conf:/etc/nginx/nginx.conf
    depends_on:
      - wsapi
      - api
    networks:
      - app-network

  wsapi:
    container_name: wsapi
    build:
      context: .
      dockerfile: serverws.dockerfile
    expose:
      - "80"
    environment:
      - CONFIG_PATH=/root/config/config.json
    depends_on:
      - redis
    networks:
      - app-network

  api:
    container_name: api
    build:
      context: .
      dockerfile: ./api/api.dockerfile
    expose:
      - "8080"
    networks:
      - app-network
    depends_on:
      - redis
      - postgres
      
  loginworker:
    container_name: loginworker
    build:
      context: .
      dockerfile: loginworker.dockerfile
    expose:
      - "8081"  # Expose port 8081 internally
    networks:
      - app-network
    depends_on:
      - postgres

  roomworker:
    container_name: roomworker
    build:
      context: .
      dockerfile: roomworker.dockerfile
    depends_on:
      - redis
    networks:
      - app-network

  broadcastworker:
    container_name: broadcastworker
    build:
      context: .
      dockerfile: broadcastworker.dockerfile
    depends_on:
      - redis
    networks:
      - app-network

  gameworker:
    container_name: gameworker
    build:
      context: .
      dockerfile: gameworker.dockerfile
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: checkersdb
      POSTGRES_DB: checkers
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge