services:
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: checkersdb
      POSTGRES_DB: checkers
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sa -d checkers"]
      interval: 5s
      timeout: 5s
      retries: 10
      
  wsapi:
    container_name: wsapi
    build:
      context: .                    # Root of the project
      dockerfile: wsapi.dockerfile  # Dockerfile in the root
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - redis
      - postgres

  api:
    container_name: api
    build:
      context: .                    # Root of the project
      dockerfile: ./api/api.dockerfile  # Dockerfile in the root
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - postgres

  pstatusworker:
    container_name: pstatusworker
    build:
      context: .
      dockerfile: pstatusworker.dockerfile
    depends_on:
      - redis
      - postgres

  roomworker:
    container_name: roomworker
    build:
      context: .
      dockerfile: roomworker.dockerfile
    depends_on:
      - redis
      - postgres

  broadcastworker:
    container_name: broadcastworker
    build:
      context: .
      dockerfile: broadcastworker.dockerfile
    depends_on:
      - redis
      - postgres

  gameworker:
    container_name: gameworker
    build:
      context: .
      dockerfile: gameworker.dockerfile
    depends_on:
      - redis
      - postgres

  

volumes:
  postgres_data: