package redisdb

import "checkers-server/models"

// Mock players data TODO: Move this to the propper DB.
var MockPlayers = map[string]models.Player{
	"token123": {
		ID:             "1",
		Token:          "token123",
		RoomID:         "room1",
		SessionID:      "session1",
		Currency:       "USD",
		CurrencyAmount: 1000,
		Status:         "OFFLINE",
		SelectedBet:    50,
		Name:           "PlayerOne",
	},
	"token456": {
		ID:             "2",
		Token:          "token456",
		RoomID:         "room2",
		SessionID:      "session2",
		Currency:       "EUR",
		CurrencyAmount: 500,
		Status:         "OFFLINE",
		SelectedBet:    20,
		Name:           "PlayerTwo",
	},
	"token789": {
		ID:             "3",
		Token:          "token789",
		RoomID:         "room3",
		SessionID:      "session3",
		Currency:       "GBP",
		CurrencyAmount: 1200,
		Status:         "OFFLINE",
		SelectedBet:    150,
		Name:           "PlayerThree",
	},
	"token101": {
		ID:             "4",
		Token:          "token101",
		RoomID:         "room4",
		SessionID:      "session4",
		Currency:       "USD",
		CurrencyAmount: 2000,
		Status:         "OFFLINE",
		SelectedBet:    100,
		Name:           "PlayerFour",
	},
	"token102": {
		ID:             "5",
		Token:          "token102",
		RoomID:         "room5",
		SessionID:      "session5",
		Currency:       "EUR",
		CurrencyAmount: 700,
		Status:         "OFFLINE",
		SelectedBet:    80,
		Name:           "PlayerFive",
	},
	"token103": {
		ID:             "6",
		Token:          "token103",
		RoomID:         "room6",
		SessionID:      "session6",
		Currency:       "JPY",
		CurrencyAmount: 300,
		Status:         "OFFLINE",
		SelectedBet:    30,
		Name:           "PlayerSix",
	},
	"token104": {
		ID:             "7",
		Token:          "token104",
		RoomID:         "room7",
		SessionID:      "session7",
		Currency:       "AUD",
		CurrencyAmount: 900,
		Status:         "OFFLINE",
		SelectedBet:    25,
		Name:           "PlayerSeven",
	},
	"token105": {
		ID:             "8",
		Token:          "token105",
		RoomID:         "room8",
		SessionID:      "session8",
		Currency:       "CAD",
		CurrencyAmount: 1100,
		Status:         "OFFLINE",
		SelectedBet:    200,
		Name:           "PlayerEight",
	},
	"token106": {
		ID:             "9",
		Token:          "token106",
		RoomID:         "room9",
		SessionID:      "session9",
		Currency:       "USD",
		CurrencyAmount: 1500,
		Status:         "OFFLINE",
		SelectedBet:    60,
		Name:           "PlayerNine",
	},
	"token107": {
		ID:             "10",
		Token:          "token107",
		RoomID:         "room10",
		SessionID:      "session10",
		Currency:       "GBP",
		CurrencyAmount: 1300,
		Status:         "OFFLINE",
		SelectedBet:    90,
		Name:           "PlayerTen",
	},
}
