FROM golang:1.23.6-alpine AS builder
WORKDIR /app/

COPY ../../go.mod ../../go.sum ./
RUN go mod download

COPY ../../ ./
WORKDIR /app/cmd/broadcastworker
RUN go build -o broadcastworker .

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/cmd/broadcastworker/broadcastworker ./
COPY --from=builder /app/internal/config/config.json ./config/config.json

ENV CONFIG_PATH=/root/config/config.json
CMD ["./broadcastworker"]
