// Code generated by ent, DO NOT EDIT.

package currency

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Lavizord/checkers-server/postgrescli/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Currency {
	return predicate.Currency(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Currency {
	return predicate.Currency(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Currency {
	return predicate.Currency(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Currency {
	return predicate.Currency(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Currency {
	return predicate.Currency(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Currency {
	return predicate.Currency(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Currency {
	return predicate.Currency(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Currency {
	return predicate.Currency(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Currency {
	return predicate.Currency(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Currency {
	return predicate.Currency(sql.FieldEQ(FieldName, v))
}

// Symbol applies equality check predicate on the "symbol" field. It's identical to SymbolEQ.
func Symbol(v string) predicate.Currency {
	return predicate.Currency(sql.FieldEQ(FieldSymbol, v))
}

// ThousandsSeparator applies equality check predicate on the "thousands_separator" field. It's identical to ThousandsSeparatorEQ.
func ThousandsSeparator(v string) predicate.Currency {
	return predicate.Currency(sql.FieldEQ(FieldThousandsSeparator, v))
}

// UnitsSeparator applies equality check predicate on the "units_separator" field. It's identical to UnitsSeparatorEQ.
func UnitsSeparator(v string) predicate.Currency {
	return predicate.Currency(sql.FieldEQ(FieldUnitsSeparator, v))
}

// SymbolPosition applies equality check predicate on the "symbol_position" field. It's identical to SymbolPositionEQ.
func SymbolPosition(v string) predicate.Currency {
	return predicate.Currency(sql.FieldEQ(FieldSymbolPosition, v))
}

// Denominator applies equality check predicate on the "denominator" field. It's identical to DenominatorEQ.
func Denominator(v int) predicate.Currency {
	return predicate.Currency(sql.FieldEQ(FieldDenominator, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Currency {
	return predicate.Currency(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Currency {
	return predicate.Currency(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Currency {
	return predicate.Currency(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Currency {
	return predicate.Currency(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Currency {
	return predicate.Currency(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Currency {
	return predicate.Currency(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Currency {
	return predicate.Currency(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Currency {
	return predicate.Currency(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Currency {
	return predicate.Currency(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Currency {
	return predicate.Currency(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Currency {
	return predicate.Currency(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Currency {
	return predicate.Currency(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Currency {
	return predicate.Currency(sql.FieldContainsFold(FieldName, v))
}

// SymbolEQ applies the EQ predicate on the "symbol" field.
func SymbolEQ(v string) predicate.Currency {
	return predicate.Currency(sql.FieldEQ(FieldSymbol, v))
}

// SymbolNEQ applies the NEQ predicate on the "symbol" field.
func SymbolNEQ(v string) predicate.Currency {
	return predicate.Currency(sql.FieldNEQ(FieldSymbol, v))
}

// SymbolIn applies the In predicate on the "symbol" field.
func SymbolIn(vs ...string) predicate.Currency {
	return predicate.Currency(sql.FieldIn(FieldSymbol, vs...))
}

// SymbolNotIn applies the NotIn predicate on the "symbol" field.
func SymbolNotIn(vs ...string) predicate.Currency {
	return predicate.Currency(sql.FieldNotIn(FieldSymbol, vs...))
}

// SymbolGT applies the GT predicate on the "symbol" field.
func SymbolGT(v string) predicate.Currency {
	return predicate.Currency(sql.FieldGT(FieldSymbol, v))
}

// SymbolGTE applies the GTE predicate on the "symbol" field.
func SymbolGTE(v string) predicate.Currency {
	return predicate.Currency(sql.FieldGTE(FieldSymbol, v))
}

// SymbolLT applies the LT predicate on the "symbol" field.
func SymbolLT(v string) predicate.Currency {
	return predicate.Currency(sql.FieldLT(FieldSymbol, v))
}

// SymbolLTE applies the LTE predicate on the "symbol" field.
func SymbolLTE(v string) predicate.Currency {
	return predicate.Currency(sql.FieldLTE(FieldSymbol, v))
}

// SymbolContains applies the Contains predicate on the "symbol" field.
func SymbolContains(v string) predicate.Currency {
	return predicate.Currency(sql.FieldContains(FieldSymbol, v))
}

// SymbolHasPrefix applies the HasPrefix predicate on the "symbol" field.
func SymbolHasPrefix(v string) predicate.Currency {
	return predicate.Currency(sql.FieldHasPrefix(FieldSymbol, v))
}

// SymbolHasSuffix applies the HasSuffix predicate on the "symbol" field.
func SymbolHasSuffix(v string) predicate.Currency {
	return predicate.Currency(sql.FieldHasSuffix(FieldSymbol, v))
}

// SymbolEqualFold applies the EqualFold predicate on the "symbol" field.
func SymbolEqualFold(v string) predicate.Currency {
	return predicate.Currency(sql.FieldEqualFold(FieldSymbol, v))
}

// SymbolContainsFold applies the ContainsFold predicate on the "symbol" field.
func SymbolContainsFold(v string) predicate.Currency {
	return predicate.Currency(sql.FieldContainsFold(FieldSymbol, v))
}

// ThousandsSeparatorEQ applies the EQ predicate on the "thousands_separator" field.
func ThousandsSeparatorEQ(v string) predicate.Currency {
	return predicate.Currency(sql.FieldEQ(FieldThousandsSeparator, v))
}

// ThousandsSeparatorNEQ applies the NEQ predicate on the "thousands_separator" field.
func ThousandsSeparatorNEQ(v string) predicate.Currency {
	return predicate.Currency(sql.FieldNEQ(FieldThousandsSeparator, v))
}

// ThousandsSeparatorIn applies the In predicate on the "thousands_separator" field.
func ThousandsSeparatorIn(vs ...string) predicate.Currency {
	return predicate.Currency(sql.FieldIn(FieldThousandsSeparator, vs...))
}

// ThousandsSeparatorNotIn applies the NotIn predicate on the "thousands_separator" field.
func ThousandsSeparatorNotIn(vs ...string) predicate.Currency {
	return predicate.Currency(sql.FieldNotIn(FieldThousandsSeparator, vs...))
}

// ThousandsSeparatorGT applies the GT predicate on the "thousands_separator" field.
func ThousandsSeparatorGT(v string) predicate.Currency {
	return predicate.Currency(sql.FieldGT(FieldThousandsSeparator, v))
}

// ThousandsSeparatorGTE applies the GTE predicate on the "thousands_separator" field.
func ThousandsSeparatorGTE(v string) predicate.Currency {
	return predicate.Currency(sql.FieldGTE(FieldThousandsSeparator, v))
}

// ThousandsSeparatorLT applies the LT predicate on the "thousands_separator" field.
func ThousandsSeparatorLT(v string) predicate.Currency {
	return predicate.Currency(sql.FieldLT(FieldThousandsSeparator, v))
}

// ThousandsSeparatorLTE applies the LTE predicate on the "thousands_separator" field.
func ThousandsSeparatorLTE(v string) predicate.Currency {
	return predicate.Currency(sql.FieldLTE(FieldThousandsSeparator, v))
}

// ThousandsSeparatorContains applies the Contains predicate on the "thousands_separator" field.
func ThousandsSeparatorContains(v string) predicate.Currency {
	return predicate.Currency(sql.FieldContains(FieldThousandsSeparator, v))
}

// ThousandsSeparatorHasPrefix applies the HasPrefix predicate on the "thousands_separator" field.
func ThousandsSeparatorHasPrefix(v string) predicate.Currency {
	return predicate.Currency(sql.FieldHasPrefix(FieldThousandsSeparator, v))
}

// ThousandsSeparatorHasSuffix applies the HasSuffix predicate on the "thousands_separator" field.
func ThousandsSeparatorHasSuffix(v string) predicate.Currency {
	return predicate.Currency(sql.FieldHasSuffix(FieldThousandsSeparator, v))
}

// ThousandsSeparatorEqualFold applies the EqualFold predicate on the "thousands_separator" field.
func ThousandsSeparatorEqualFold(v string) predicate.Currency {
	return predicate.Currency(sql.FieldEqualFold(FieldThousandsSeparator, v))
}

// ThousandsSeparatorContainsFold applies the ContainsFold predicate on the "thousands_separator" field.
func ThousandsSeparatorContainsFold(v string) predicate.Currency {
	return predicate.Currency(sql.FieldContainsFold(FieldThousandsSeparator, v))
}

// UnitsSeparatorEQ applies the EQ predicate on the "units_separator" field.
func UnitsSeparatorEQ(v string) predicate.Currency {
	return predicate.Currency(sql.FieldEQ(FieldUnitsSeparator, v))
}

// UnitsSeparatorNEQ applies the NEQ predicate on the "units_separator" field.
func UnitsSeparatorNEQ(v string) predicate.Currency {
	return predicate.Currency(sql.FieldNEQ(FieldUnitsSeparator, v))
}

// UnitsSeparatorIn applies the In predicate on the "units_separator" field.
func UnitsSeparatorIn(vs ...string) predicate.Currency {
	return predicate.Currency(sql.FieldIn(FieldUnitsSeparator, vs...))
}

// UnitsSeparatorNotIn applies the NotIn predicate on the "units_separator" field.
func UnitsSeparatorNotIn(vs ...string) predicate.Currency {
	return predicate.Currency(sql.FieldNotIn(FieldUnitsSeparator, vs...))
}

// UnitsSeparatorGT applies the GT predicate on the "units_separator" field.
func UnitsSeparatorGT(v string) predicate.Currency {
	return predicate.Currency(sql.FieldGT(FieldUnitsSeparator, v))
}

// UnitsSeparatorGTE applies the GTE predicate on the "units_separator" field.
func UnitsSeparatorGTE(v string) predicate.Currency {
	return predicate.Currency(sql.FieldGTE(FieldUnitsSeparator, v))
}

// UnitsSeparatorLT applies the LT predicate on the "units_separator" field.
func UnitsSeparatorLT(v string) predicate.Currency {
	return predicate.Currency(sql.FieldLT(FieldUnitsSeparator, v))
}

// UnitsSeparatorLTE applies the LTE predicate on the "units_separator" field.
func UnitsSeparatorLTE(v string) predicate.Currency {
	return predicate.Currency(sql.FieldLTE(FieldUnitsSeparator, v))
}

// UnitsSeparatorContains applies the Contains predicate on the "units_separator" field.
func UnitsSeparatorContains(v string) predicate.Currency {
	return predicate.Currency(sql.FieldContains(FieldUnitsSeparator, v))
}

// UnitsSeparatorHasPrefix applies the HasPrefix predicate on the "units_separator" field.
func UnitsSeparatorHasPrefix(v string) predicate.Currency {
	return predicate.Currency(sql.FieldHasPrefix(FieldUnitsSeparator, v))
}

// UnitsSeparatorHasSuffix applies the HasSuffix predicate on the "units_separator" field.
func UnitsSeparatorHasSuffix(v string) predicate.Currency {
	return predicate.Currency(sql.FieldHasSuffix(FieldUnitsSeparator, v))
}

// UnitsSeparatorEqualFold applies the EqualFold predicate on the "units_separator" field.
func UnitsSeparatorEqualFold(v string) predicate.Currency {
	return predicate.Currency(sql.FieldEqualFold(FieldUnitsSeparator, v))
}

// UnitsSeparatorContainsFold applies the ContainsFold predicate on the "units_separator" field.
func UnitsSeparatorContainsFold(v string) predicate.Currency {
	return predicate.Currency(sql.FieldContainsFold(FieldUnitsSeparator, v))
}

// SymbolPositionEQ applies the EQ predicate on the "symbol_position" field.
func SymbolPositionEQ(v string) predicate.Currency {
	return predicate.Currency(sql.FieldEQ(FieldSymbolPosition, v))
}

// SymbolPositionNEQ applies the NEQ predicate on the "symbol_position" field.
func SymbolPositionNEQ(v string) predicate.Currency {
	return predicate.Currency(sql.FieldNEQ(FieldSymbolPosition, v))
}

// SymbolPositionIn applies the In predicate on the "symbol_position" field.
func SymbolPositionIn(vs ...string) predicate.Currency {
	return predicate.Currency(sql.FieldIn(FieldSymbolPosition, vs...))
}

// SymbolPositionNotIn applies the NotIn predicate on the "symbol_position" field.
func SymbolPositionNotIn(vs ...string) predicate.Currency {
	return predicate.Currency(sql.FieldNotIn(FieldSymbolPosition, vs...))
}

// SymbolPositionGT applies the GT predicate on the "symbol_position" field.
func SymbolPositionGT(v string) predicate.Currency {
	return predicate.Currency(sql.FieldGT(FieldSymbolPosition, v))
}

// SymbolPositionGTE applies the GTE predicate on the "symbol_position" field.
func SymbolPositionGTE(v string) predicate.Currency {
	return predicate.Currency(sql.FieldGTE(FieldSymbolPosition, v))
}

// SymbolPositionLT applies the LT predicate on the "symbol_position" field.
func SymbolPositionLT(v string) predicate.Currency {
	return predicate.Currency(sql.FieldLT(FieldSymbolPosition, v))
}

// SymbolPositionLTE applies the LTE predicate on the "symbol_position" field.
func SymbolPositionLTE(v string) predicate.Currency {
	return predicate.Currency(sql.FieldLTE(FieldSymbolPosition, v))
}

// SymbolPositionContains applies the Contains predicate on the "symbol_position" field.
func SymbolPositionContains(v string) predicate.Currency {
	return predicate.Currency(sql.FieldContains(FieldSymbolPosition, v))
}

// SymbolPositionHasPrefix applies the HasPrefix predicate on the "symbol_position" field.
func SymbolPositionHasPrefix(v string) predicate.Currency {
	return predicate.Currency(sql.FieldHasPrefix(FieldSymbolPosition, v))
}

// SymbolPositionHasSuffix applies the HasSuffix predicate on the "symbol_position" field.
func SymbolPositionHasSuffix(v string) predicate.Currency {
	return predicate.Currency(sql.FieldHasSuffix(FieldSymbolPosition, v))
}

// SymbolPositionEqualFold applies the EqualFold predicate on the "symbol_position" field.
func SymbolPositionEqualFold(v string) predicate.Currency {
	return predicate.Currency(sql.FieldEqualFold(FieldSymbolPosition, v))
}

// SymbolPositionContainsFold applies the ContainsFold predicate on the "symbol_position" field.
func SymbolPositionContainsFold(v string) predicate.Currency {
	return predicate.Currency(sql.FieldContainsFold(FieldSymbolPosition, v))
}

// DenominatorEQ applies the EQ predicate on the "denominator" field.
func DenominatorEQ(v int) predicate.Currency {
	return predicate.Currency(sql.FieldEQ(FieldDenominator, v))
}

// DenominatorNEQ applies the NEQ predicate on the "denominator" field.
func DenominatorNEQ(v int) predicate.Currency {
	return predicate.Currency(sql.FieldNEQ(FieldDenominator, v))
}

// DenominatorIn applies the In predicate on the "denominator" field.
func DenominatorIn(vs ...int) predicate.Currency {
	return predicate.Currency(sql.FieldIn(FieldDenominator, vs...))
}

// DenominatorNotIn applies the NotIn predicate on the "denominator" field.
func DenominatorNotIn(vs ...int) predicate.Currency {
	return predicate.Currency(sql.FieldNotIn(FieldDenominator, vs...))
}

// DenominatorGT applies the GT predicate on the "denominator" field.
func DenominatorGT(v int) predicate.Currency {
	return predicate.Currency(sql.FieldGT(FieldDenominator, v))
}

// DenominatorGTE applies the GTE predicate on the "denominator" field.
func DenominatorGTE(v int) predicate.Currency {
	return predicate.Currency(sql.FieldGTE(FieldDenominator, v))
}

// DenominatorLT applies the LT predicate on the "denominator" field.
func DenominatorLT(v int) predicate.Currency {
	return predicate.Currency(sql.FieldLT(FieldDenominator, v))
}

// DenominatorLTE applies the LTE predicate on the "denominator" field.
func DenominatorLTE(v int) predicate.Currency {
	return predicate.Currency(sql.FieldLTE(FieldDenominator, v))
}

// HasCurrencyVersions applies the HasEdge predicate on the "currency_versions" edge.
func HasCurrencyVersions() predicate.Currency {
	return predicate.Currency(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CurrencyVersionsTable, CurrencyVersionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCurrencyVersionsWith applies the HasEdge predicate on the "currency_versions" edge with a given conditions (other predicates).
func HasCurrencyVersionsWith(preds ...predicate.CurrencyVersion) predicate.Currency {
	return predicate.Currency(func(s *sql.Selector) {
		step := newCurrencyVersionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Currency) predicate.Currency {
	return predicate.Currency(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Currency) predicate.Currency {
	return predicate.Currency(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Currency) predicate.Currency {
	return predicate.Currency(sql.NotPredicates(p))
}
