// Code generated by ent, DO NOT EDIT.

package gametype

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Lavizord/checkers-server/postgrescli/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.GameType {
	return predicate.GameType(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.GameType {
	return predicate.GameType(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.GameType {
	return predicate.GameType(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.GameType {
	return predicate.GameType(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.GameType {
	return predicate.GameType(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.GameType {
	return predicate.GameType(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.GameType {
	return predicate.GameType(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.GameType {
	return predicate.GameType(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.GameType {
	return predicate.GameType(sql.FieldLTE(FieldID, id))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.GameType {
	return predicate.GameType(sql.FieldEQ(FieldType, v))
}

// ExternalTypeID applies equality check predicate on the "external_type_id" field. It's identical to ExternalTypeIDEQ.
func ExternalTypeID(v string) predicate.GameType {
	return predicate.GameType(sql.FieldEQ(FieldExternalTypeID, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.GameType {
	return predicate.GameType(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.GameType {
	return predicate.GameType(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.GameType {
	return predicate.GameType(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.GameType {
	return predicate.GameType(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.GameType {
	return predicate.GameType(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.GameType {
	return predicate.GameType(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.GameType {
	return predicate.GameType(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.GameType {
	return predicate.GameType(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.GameType {
	return predicate.GameType(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.GameType {
	return predicate.GameType(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.GameType {
	return predicate.GameType(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.GameType {
	return predicate.GameType(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.GameType {
	return predicate.GameType(sql.FieldContainsFold(FieldType, v))
}

// ExternalTypeIDEQ applies the EQ predicate on the "external_type_id" field.
func ExternalTypeIDEQ(v string) predicate.GameType {
	return predicate.GameType(sql.FieldEQ(FieldExternalTypeID, v))
}

// ExternalTypeIDNEQ applies the NEQ predicate on the "external_type_id" field.
func ExternalTypeIDNEQ(v string) predicate.GameType {
	return predicate.GameType(sql.FieldNEQ(FieldExternalTypeID, v))
}

// ExternalTypeIDIn applies the In predicate on the "external_type_id" field.
func ExternalTypeIDIn(vs ...string) predicate.GameType {
	return predicate.GameType(sql.FieldIn(FieldExternalTypeID, vs...))
}

// ExternalTypeIDNotIn applies the NotIn predicate on the "external_type_id" field.
func ExternalTypeIDNotIn(vs ...string) predicate.GameType {
	return predicate.GameType(sql.FieldNotIn(FieldExternalTypeID, vs...))
}

// ExternalTypeIDGT applies the GT predicate on the "external_type_id" field.
func ExternalTypeIDGT(v string) predicate.GameType {
	return predicate.GameType(sql.FieldGT(FieldExternalTypeID, v))
}

// ExternalTypeIDGTE applies the GTE predicate on the "external_type_id" field.
func ExternalTypeIDGTE(v string) predicate.GameType {
	return predicate.GameType(sql.FieldGTE(FieldExternalTypeID, v))
}

// ExternalTypeIDLT applies the LT predicate on the "external_type_id" field.
func ExternalTypeIDLT(v string) predicate.GameType {
	return predicate.GameType(sql.FieldLT(FieldExternalTypeID, v))
}

// ExternalTypeIDLTE applies the LTE predicate on the "external_type_id" field.
func ExternalTypeIDLTE(v string) predicate.GameType {
	return predicate.GameType(sql.FieldLTE(FieldExternalTypeID, v))
}

// ExternalTypeIDContains applies the Contains predicate on the "external_type_id" field.
func ExternalTypeIDContains(v string) predicate.GameType {
	return predicate.GameType(sql.FieldContains(FieldExternalTypeID, v))
}

// ExternalTypeIDHasPrefix applies the HasPrefix predicate on the "external_type_id" field.
func ExternalTypeIDHasPrefix(v string) predicate.GameType {
	return predicate.GameType(sql.FieldHasPrefix(FieldExternalTypeID, v))
}

// ExternalTypeIDHasSuffix applies the HasSuffix predicate on the "external_type_id" field.
func ExternalTypeIDHasSuffix(v string) predicate.GameType {
	return predicate.GameType(sql.FieldHasSuffix(FieldExternalTypeID, v))
}

// ExternalTypeIDEqualFold applies the EqualFold predicate on the "external_type_id" field.
func ExternalTypeIDEqualFold(v string) predicate.GameType {
	return predicate.GameType(sql.FieldEqualFold(FieldExternalTypeID, v))
}

// ExternalTypeIDContainsFold applies the ContainsFold predicate on the "external_type_id" field.
func ExternalTypeIDContainsFold(v string) predicate.GameType {
	return predicate.GameType(sql.FieldContainsFold(FieldExternalTypeID, v))
}

// HasGames applies the HasEdge predicate on the "games" edge.
func HasGames() predicate.GameType {
	return predicate.GameType(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, GamesTable, GamesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGamesWith applies the HasEdge predicate on the "games" edge with a given conditions (other predicates).
func HasGamesWith(preds ...predicate.Game) predicate.GameType {
	return predicate.GameType(func(s *sql.Selector) {
		step := newGamesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGameVersions applies the HasEdge predicate on the "game_versions" edge.
func HasGameVersions() predicate.GameType {
	return predicate.GameType(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, GameVersionsTable, GameVersionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGameVersionsWith applies the HasEdge predicate on the "game_versions" edge with a given conditions (other predicates).
func HasGameVersionsWith(preds ...predicate.GameVersion) predicate.GameType {
	return predicate.GameType(func(s *sql.Selector) {
		step := newGameVersionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCurrencyVersions applies the HasEdge predicate on the "currency_versions" edge.
func HasCurrencyVersions() predicate.GameType {
	return predicate.GameType(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CurrencyVersionsTable, CurrencyVersionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCurrencyVersionsWith applies the HasEdge predicate on the "currency_versions" edge with a given conditions (other predicates).
func HasCurrencyVersionsWith(preds ...predicate.CurrencyVersion) predicate.GameType {
	return predicate.GameType(func(s *sql.Selector) {
		step := newCurrencyVersionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GameType) predicate.GameType {
	return predicate.GameType(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GameType) predicate.GameType {
	return predicate.GameType(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GameType) predicate.GameType {
	return predicate.GameType(sql.NotPredicates(p))
}
