// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Lavizord/checkers-server/postgrescli/ent/gameconfig"
	"github.com/Lavizord/checkers-server/postgrescli/ent/predicate"
)

// GameConfigDelete is the builder for deleting a GameConfig entity.
type GameConfigDelete struct {
	config
	hooks    []Hook
	mutation *GameConfigMutation
}

// Where appends a list predicates to the GameConfigDelete builder.
func (gcd *GameConfigDelete) Where(ps ...predicate.GameConfig) *GameConfigDelete {
	gcd.mutation.Where(ps...)
	return gcd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (gcd *GameConfigDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, gcd.sqlExec, gcd.mutation, gcd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (gcd *GameConfigDelete) ExecX(ctx context.Context) int {
	n, err := gcd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (gcd *GameConfigDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(gameconfig.Table, sqlgraph.NewFieldSpec(gameconfig.FieldID, field.TypeInt))
	if ps := gcd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, gcd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	gcd.mutation.done = true
	return affected, err
}

// GameConfigDeleteOne is the builder for deleting a single GameConfig entity.
type GameConfigDeleteOne struct {
	gcd *GameConfigDelete
}

// Where appends a list predicates to the GameConfigDelete builder.
func (gcdo *GameConfigDeleteOne) Where(ps ...predicate.GameConfig) *GameConfigDeleteOne {
	gcdo.gcd.mutation.Where(ps...)
	return gcdo
}

// Exec executes the deletion query.
func (gcdo *GameConfigDeleteOne) Exec(ctx context.Context) error {
	n, err := gcdo.gcd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{gameconfig.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (gcdo *GameConfigDeleteOne) ExecX(ctx context.Context) {
	if err := gcdo.Exec(ctx); err != nil {
		panic(err)
	}
}
