// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Lavizord/checkers-server/postgrescli/ent/mathversion"
	"github.com/Lavizord/checkers-server/postgrescli/ent/predicate"
)

// MathVersionDelete is the builder for deleting a MathVersion entity.
type MathVersionDelete struct {
	config
	hooks    []Hook
	mutation *MathVersionMutation
}

// Where appends a list predicates to the MathVersionDelete builder.
func (mvd *MathVersionDelete) Where(ps ...predicate.MathVersion) *MathVersionDelete {
	mvd.mutation.Where(ps...)
	return mvd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (mvd *MathVersionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, mvd.sqlExec, mvd.mutation, mvd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (mvd *MathVersionDelete) ExecX(ctx context.Context) int {
	n, err := mvd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (mvd *MathVersionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(mathversion.Table, sqlgraph.NewFieldSpec(mathversion.FieldID, field.TypeInt))
	if ps := mvd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, mvd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	mvd.mutation.done = true
	return affected, err
}

// MathVersionDeleteOne is the builder for deleting a single MathVersion entity.
type MathVersionDeleteOne struct {
	mvd *MathVersionDelete
}

// Where appends a list predicates to the MathVersionDelete builder.
func (mvdo *MathVersionDeleteOne) Where(ps ...predicate.MathVersion) *MathVersionDeleteOne {
	mvdo.mvd.mutation.Where(ps...)
	return mvdo
}

// Exec executes the deletion query.
func (mvdo *MathVersionDeleteOne) Exec(ctx context.Context) error {
	n, err := mvdo.mvd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{mathversion.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (mvdo *MathVersionDeleteOne) ExecX(ctx context.Context) {
	if err := mvdo.Exec(ctx); err != nil {
		panic(err)
	}
}
