// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Lavizord/checkers-server/postgrescli/ent/game"
	"github.com/Lavizord/checkers-server/postgrescli/ent/serie"
	"github.com/Lavizord/checkers-server/postgrescli/ent/seriefeature"
)

// SerieCreate is the builder for creating a Serie entity.
type SerieCreate struct {
	config
	mutation *SerieMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (sc *SerieCreate) SetName(s string) *SerieCreate {
	sc.mutation.SetName(s)
	return sc
}

// SetCreatedAt sets the "created_at" field.
func (sc *SerieCreate) SetCreatedAt(t time.Time) *SerieCreate {
	sc.mutation.SetCreatedAt(t)
	return sc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (sc *SerieCreate) SetNillableCreatedAt(t *time.Time) *SerieCreate {
	if t != nil {
		sc.SetCreatedAt(*t)
	}
	return sc
}

// SetDeletedAt sets the "deleted_at" field.
func (sc *SerieCreate) SetDeletedAt(t time.Time) *SerieCreate {
	sc.mutation.SetDeletedAt(t)
	return sc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (sc *SerieCreate) SetNillableDeletedAt(t *time.Time) *SerieCreate {
	if t != nil {
		sc.SetDeletedAt(*t)
	}
	return sc
}

// SetExternalID sets the "external_id" field.
func (sc *SerieCreate) SetExternalID(s string) *SerieCreate {
	sc.mutation.SetExternalID(s)
	return sc
}

// AddGameIDs adds the "games" edge to the Game entity by IDs.
func (sc *SerieCreate) AddGameIDs(ids ...int) *SerieCreate {
	sc.mutation.AddGameIDs(ids...)
	return sc
}

// AddGames adds the "games" edges to the Game entity.
func (sc *SerieCreate) AddGames(g ...*Game) *SerieCreate {
	ids := make([]int, len(g))
	for i := range g {
		ids[i] = g[i].ID
	}
	return sc.AddGameIDs(ids...)
}

// AddSerieFeatureIDs adds the "serie_features" edge to the SerieFeature entity by IDs.
func (sc *SerieCreate) AddSerieFeatureIDs(ids ...int) *SerieCreate {
	sc.mutation.AddSerieFeatureIDs(ids...)
	return sc
}

// AddSerieFeatures adds the "serie_features" edges to the SerieFeature entity.
func (sc *SerieCreate) AddSerieFeatures(s ...*SerieFeature) *SerieCreate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return sc.AddSerieFeatureIDs(ids...)
}

// Mutation returns the SerieMutation object of the builder.
func (sc *SerieCreate) Mutation() *SerieMutation {
	return sc.mutation
}

// Save creates the Serie in the database.
func (sc *SerieCreate) Save(ctx context.Context) (*Serie, error) {
	sc.defaults()
	return withHooks(ctx, sc.sqlSave, sc.mutation, sc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sc *SerieCreate) SaveX(ctx context.Context) *Serie {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sc *SerieCreate) Exec(ctx context.Context) error {
	_, err := sc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sc *SerieCreate) ExecX(ctx context.Context) {
	if err := sc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sc *SerieCreate) defaults() {
	if _, ok := sc.mutation.CreatedAt(); !ok {
		v := serie.DefaultCreatedAt()
		sc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sc *SerieCreate) check() error {
	if _, ok := sc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Serie.name"`)}
	}
	if _, ok := sc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Serie.created_at"`)}
	}
	if _, ok := sc.mutation.ExternalID(); !ok {
		return &ValidationError{Name: "external_id", err: errors.New(`ent: missing required field "Serie.external_id"`)}
	}
	return nil
}

func (sc *SerieCreate) sqlSave(ctx context.Context) (*Serie, error) {
	if err := sc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	sc.mutation.id = &_node.ID
	sc.mutation.done = true
	return _node, nil
}

func (sc *SerieCreate) createSpec() (*Serie, *sqlgraph.CreateSpec) {
	var (
		_node = &Serie{config: sc.config}
		_spec = sqlgraph.NewCreateSpec(serie.Table, sqlgraph.NewFieldSpec(serie.FieldID, field.TypeInt))
	)
	if value, ok := sc.mutation.Name(); ok {
		_spec.SetField(serie.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := sc.mutation.CreatedAt(); ok {
		_spec.SetField(serie.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := sc.mutation.DeletedAt(); ok {
		_spec.SetField(serie.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := sc.mutation.ExternalID(); ok {
		_spec.SetField(serie.FieldExternalID, field.TypeString, value)
		_node.ExternalID = value
	}
	if nodes := sc.mutation.GamesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   serie.GamesTable,
			Columns: []string{serie.GamesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := sc.mutation.SerieFeaturesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   serie.SerieFeaturesTable,
			Columns: []string{serie.SerieFeaturesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seriefeature.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SerieCreateBulk is the builder for creating many Serie entities in bulk.
type SerieCreateBulk struct {
	config
	err      error
	builders []*SerieCreate
}

// Save creates the Serie entities in the database.
func (scb *SerieCreateBulk) Save(ctx context.Context) ([]*Serie, error) {
	if scb.err != nil {
		return nil, scb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*Serie, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SerieMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scb *SerieCreateBulk) SaveX(ctx context.Context) []*Serie {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scb *SerieCreateBulk) Exec(ctx context.Context) error {
	_, err := scb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scb *SerieCreateBulk) ExecX(ctx context.Context) {
	if err := scb.Exec(ctx); err != nil {
		panic(err)
	}
}
