// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Lavizord/checkers-server/postgrescli/ent/game"
	"github.com/Lavizord/checkers-server/postgrescli/ent/predicate"
	"github.com/Lavizord/checkers-server/postgrescli/ent/serie"
	"github.com/Lavizord/checkers-server/postgrescli/ent/seriefeature"
)

// SerieUpdate is the builder for updating Serie entities.
type SerieUpdate struct {
	config
	hooks    []Hook
	mutation *SerieMutation
}

// Where appends a list predicates to the SerieUpdate builder.
func (su *SerieUpdate) Where(ps ...predicate.Serie) *SerieUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetName sets the "name" field.
func (su *SerieUpdate) SetName(s string) *SerieUpdate {
	su.mutation.SetName(s)
	return su
}

// SetNillableName sets the "name" field if the given value is not nil.
func (su *SerieUpdate) SetNillableName(s *string) *SerieUpdate {
	if s != nil {
		su.SetName(*s)
	}
	return su
}

// SetCreatedAt sets the "created_at" field.
func (su *SerieUpdate) SetCreatedAt(t time.Time) *SerieUpdate {
	su.mutation.SetCreatedAt(t)
	return su
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (su *SerieUpdate) SetNillableCreatedAt(t *time.Time) *SerieUpdate {
	if t != nil {
		su.SetCreatedAt(*t)
	}
	return su
}

// SetDeletedAt sets the "deleted_at" field.
func (su *SerieUpdate) SetDeletedAt(t time.Time) *SerieUpdate {
	su.mutation.SetDeletedAt(t)
	return su
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (su *SerieUpdate) SetNillableDeletedAt(t *time.Time) *SerieUpdate {
	if t != nil {
		su.SetDeletedAt(*t)
	}
	return su
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (su *SerieUpdate) ClearDeletedAt() *SerieUpdate {
	su.mutation.ClearDeletedAt()
	return su
}

// SetExternalID sets the "external_id" field.
func (su *SerieUpdate) SetExternalID(s string) *SerieUpdate {
	su.mutation.SetExternalID(s)
	return su
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (su *SerieUpdate) SetNillableExternalID(s *string) *SerieUpdate {
	if s != nil {
		su.SetExternalID(*s)
	}
	return su
}

// AddGameIDs adds the "games" edge to the Game entity by IDs.
func (su *SerieUpdate) AddGameIDs(ids ...int) *SerieUpdate {
	su.mutation.AddGameIDs(ids...)
	return su
}

// AddGames adds the "games" edges to the Game entity.
func (su *SerieUpdate) AddGames(g ...*Game) *SerieUpdate {
	ids := make([]int, len(g))
	for i := range g {
		ids[i] = g[i].ID
	}
	return su.AddGameIDs(ids...)
}

// AddSerieFeatureIDs adds the "serie_features" edge to the SerieFeature entity by IDs.
func (su *SerieUpdate) AddSerieFeatureIDs(ids ...int) *SerieUpdate {
	su.mutation.AddSerieFeatureIDs(ids...)
	return su
}

// AddSerieFeatures adds the "serie_features" edges to the SerieFeature entity.
func (su *SerieUpdate) AddSerieFeatures(s ...*SerieFeature) *SerieUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return su.AddSerieFeatureIDs(ids...)
}

// Mutation returns the SerieMutation object of the builder.
func (su *SerieUpdate) Mutation() *SerieMutation {
	return su.mutation
}

// ClearGames clears all "games" edges to the Game entity.
func (su *SerieUpdate) ClearGames() *SerieUpdate {
	su.mutation.ClearGames()
	return su
}

// RemoveGameIDs removes the "games" edge to Game entities by IDs.
func (su *SerieUpdate) RemoveGameIDs(ids ...int) *SerieUpdate {
	su.mutation.RemoveGameIDs(ids...)
	return su
}

// RemoveGames removes "games" edges to Game entities.
func (su *SerieUpdate) RemoveGames(g ...*Game) *SerieUpdate {
	ids := make([]int, len(g))
	for i := range g {
		ids[i] = g[i].ID
	}
	return su.RemoveGameIDs(ids...)
}

// ClearSerieFeatures clears all "serie_features" edges to the SerieFeature entity.
func (su *SerieUpdate) ClearSerieFeatures() *SerieUpdate {
	su.mutation.ClearSerieFeatures()
	return su
}

// RemoveSerieFeatureIDs removes the "serie_features" edge to SerieFeature entities by IDs.
func (su *SerieUpdate) RemoveSerieFeatureIDs(ids ...int) *SerieUpdate {
	su.mutation.RemoveSerieFeatureIDs(ids...)
	return su
}

// RemoveSerieFeatures removes "serie_features" edges to SerieFeature entities.
func (su *SerieUpdate) RemoveSerieFeatures(s ...*SerieFeature) *SerieUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return su.RemoveSerieFeatureIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *SerieUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *SerieUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SerieUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SerieUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

func (su *SerieUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(serie.Table, serie.Columns, sqlgraph.NewFieldSpec(serie.FieldID, field.TypeInt))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.Name(); ok {
		_spec.SetField(serie.FieldName, field.TypeString, value)
	}
	if value, ok := su.mutation.CreatedAt(); ok {
		_spec.SetField(serie.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := su.mutation.DeletedAt(); ok {
		_spec.SetField(serie.FieldDeletedAt, field.TypeTime, value)
	}
	if su.mutation.DeletedAtCleared() {
		_spec.ClearField(serie.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := su.mutation.ExternalID(); ok {
		_spec.SetField(serie.FieldExternalID, field.TypeString, value)
	}
	if su.mutation.GamesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   serie.GamesTable,
			Columns: []string{serie.GamesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.RemovedGamesIDs(); len(nodes) > 0 && !su.mutation.GamesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   serie.GamesTable,
			Columns: []string{serie.GamesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.GamesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   serie.GamesTable,
			Columns: []string{serie.GamesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if su.mutation.SerieFeaturesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   serie.SerieFeaturesTable,
			Columns: []string{serie.SerieFeaturesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seriefeature.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.RemovedSerieFeaturesIDs(); len(nodes) > 0 && !su.mutation.SerieFeaturesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   serie.SerieFeaturesTable,
			Columns: []string{serie.SerieFeaturesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seriefeature.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.SerieFeaturesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   serie.SerieFeaturesTable,
			Columns: []string{serie.SerieFeaturesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seriefeature.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{serie.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// SerieUpdateOne is the builder for updating a single Serie entity.
type SerieUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SerieMutation
}

// SetName sets the "name" field.
func (suo *SerieUpdateOne) SetName(s string) *SerieUpdateOne {
	suo.mutation.SetName(s)
	return suo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (suo *SerieUpdateOne) SetNillableName(s *string) *SerieUpdateOne {
	if s != nil {
		suo.SetName(*s)
	}
	return suo
}

// SetCreatedAt sets the "created_at" field.
func (suo *SerieUpdateOne) SetCreatedAt(t time.Time) *SerieUpdateOne {
	suo.mutation.SetCreatedAt(t)
	return suo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (suo *SerieUpdateOne) SetNillableCreatedAt(t *time.Time) *SerieUpdateOne {
	if t != nil {
		suo.SetCreatedAt(*t)
	}
	return suo
}

// SetDeletedAt sets the "deleted_at" field.
func (suo *SerieUpdateOne) SetDeletedAt(t time.Time) *SerieUpdateOne {
	suo.mutation.SetDeletedAt(t)
	return suo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (suo *SerieUpdateOne) SetNillableDeletedAt(t *time.Time) *SerieUpdateOne {
	if t != nil {
		suo.SetDeletedAt(*t)
	}
	return suo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (suo *SerieUpdateOne) ClearDeletedAt() *SerieUpdateOne {
	suo.mutation.ClearDeletedAt()
	return suo
}

// SetExternalID sets the "external_id" field.
func (suo *SerieUpdateOne) SetExternalID(s string) *SerieUpdateOne {
	suo.mutation.SetExternalID(s)
	return suo
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (suo *SerieUpdateOne) SetNillableExternalID(s *string) *SerieUpdateOne {
	if s != nil {
		suo.SetExternalID(*s)
	}
	return suo
}

// AddGameIDs adds the "games" edge to the Game entity by IDs.
func (suo *SerieUpdateOne) AddGameIDs(ids ...int) *SerieUpdateOne {
	suo.mutation.AddGameIDs(ids...)
	return suo
}

// AddGames adds the "games" edges to the Game entity.
func (suo *SerieUpdateOne) AddGames(g ...*Game) *SerieUpdateOne {
	ids := make([]int, len(g))
	for i := range g {
		ids[i] = g[i].ID
	}
	return suo.AddGameIDs(ids...)
}

// AddSerieFeatureIDs adds the "serie_features" edge to the SerieFeature entity by IDs.
func (suo *SerieUpdateOne) AddSerieFeatureIDs(ids ...int) *SerieUpdateOne {
	suo.mutation.AddSerieFeatureIDs(ids...)
	return suo
}

// AddSerieFeatures adds the "serie_features" edges to the SerieFeature entity.
func (suo *SerieUpdateOne) AddSerieFeatures(s ...*SerieFeature) *SerieUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return suo.AddSerieFeatureIDs(ids...)
}

// Mutation returns the SerieMutation object of the builder.
func (suo *SerieUpdateOne) Mutation() *SerieMutation {
	return suo.mutation
}

// ClearGames clears all "games" edges to the Game entity.
func (suo *SerieUpdateOne) ClearGames() *SerieUpdateOne {
	suo.mutation.ClearGames()
	return suo
}

// RemoveGameIDs removes the "games" edge to Game entities by IDs.
func (suo *SerieUpdateOne) RemoveGameIDs(ids ...int) *SerieUpdateOne {
	suo.mutation.RemoveGameIDs(ids...)
	return suo
}

// RemoveGames removes "games" edges to Game entities.
func (suo *SerieUpdateOne) RemoveGames(g ...*Game) *SerieUpdateOne {
	ids := make([]int, len(g))
	for i := range g {
		ids[i] = g[i].ID
	}
	return suo.RemoveGameIDs(ids...)
}

// ClearSerieFeatures clears all "serie_features" edges to the SerieFeature entity.
func (suo *SerieUpdateOne) ClearSerieFeatures() *SerieUpdateOne {
	suo.mutation.ClearSerieFeatures()
	return suo
}

// RemoveSerieFeatureIDs removes the "serie_features" edge to SerieFeature entities by IDs.
func (suo *SerieUpdateOne) RemoveSerieFeatureIDs(ids ...int) *SerieUpdateOne {
	suo.mutation.RemoveSerieFeatureIDs(ids...)
	return suo
}

// RemoveSerieFeatures removes "serie_features" edges to SerieFeature entities.
func (suo *SerieUpdateOne) RemoveSerieFeatures(s ...*SerieFeature) *SerieUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return suo.RemoveSerieFeatureIDs(ids...)
}

// Where appends a list predicates to the SerieUpdate builder.
func (suo *SerieUpdateOne) Where(ps ...predicate.Serie) *SerieUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *SerieUpdateOne) Select(field string, fields ...string) *SerieUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Serie entity.
func (suo *SerieUpdateOne) Save(ctx context.Context) (*Serie, error) {
	return withHooks(ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SerieUpdateOne) SaveX(ctx context.Context) *Serie {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *SerieUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SerieUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (suo *SerieUpdateOne) sqlSave(ctx context.Context) (_node *Serie, err error) {
	_spec := sqlgraph.NewUpdateSpec(serie.Table, serie.Columns, sqlgraph.NewFieldSpec(serie.FieldID, field.TypeInt))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Serie.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, serie.FieldID)
		for _, f := range fields {
			if !serie.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != serie.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.Name(); ok {
		_spec.SetField(serie.FieldName, field.TypeString, value)
	}
	if value, ok := suo.mutation.CreatedAt(); ok {
		_spec.SetField(serie.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := suo.mutation.DeletedAt(); ok {
		_spec.SetField(serie.FieldDeletedAt, field.TypeTime, value)
	}
	if suo.mutation.DeletedAtCleared() {
		_spec.ClearField(serie.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := suo.mutation.ExternalID(); ok {
		_spec.SetField(serie.FieldExternalID, field.TypeString, value)
	}
	if suo.mutation.GamesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   serie.GamesTable,
			Columns: []string{serie.GamesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.RemovedGamesIDs(); len(nodes) > 0 && !suo.mutation.GamesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   serie.GamesTable,
			Columns: []string{serie.GamesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.GamesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   serie.GamesTable,
			Columns: []string{serie.GamesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if suo.mutation.SerieFeaturesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   serie.SerieFeaturesTable,
			Columns: []string{serie.SerieFeaturesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seriefeature.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.RemovedSerieFeaturesIDs(); len(nodes) > 0 && !suo.mutation.SerieFeaturesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   serie.SerieFeaturesTable,
			Columns: []string{serie.SerieFeaturesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seriefeature.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.SerieFeaturesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   serie.SerieFeaturesTable,
			Columns: []string{serie.SerieFeaturesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seriefeature.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Serie{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{serie.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
