// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Lavizord/checkers-server/postgrescli/ent/predicate"
	"github.com/Lavizord/checkers-server/postgrescli/ent/seriefeature"
)

// SerieFeatureDelete is the builder for deleting a SerieFeature entity.
type SerieFeatureDelete struct {
	config
	hooks    []Hook
	mutation *SerieFeatureMutation
}

// Where appends a list predicates to the SerieFeatureDelete builder.
func (sfd *SerieFeatureDelete) Where(ps ...predicate.SerieFeature) *SerieFeatureDelete {
	sfd.mutation.Where(ps...)
	return sfd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sfd *SerieFeatureDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, sfd.sqlExec, sfd.mutation, sfd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (sfd *SerieFeatureDelete) ExecX(ctx context.Context) int {
	n, err := sfd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sfd *SerieFeatureDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(seriefeature.Table, sqlgraph.NewFieldSpec(seriefeature.FieldID, field.TypeInt))
	if ps := sfd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, sfd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	sfd.mutation.done = true
	return affected, err
}

// SerieFeatureDeleteOne is the builder for deleting a single SerieFeature entity.
type SerieFeatureDeleteOne struct {
	sfd *SerieFeatureDelete
}

// Where appends a list predicates to the SerieFeatureDelete builder.
func (sfdo *SerieFeatureDeleteOne) Where(ps ...predicate.SerieFeature) *SerieFeatureDeleteOne {
	sfdo.sfd.mutation.Where(ps...)
	return sfdo
}

// Exec executes the deletion query.
func (sfdo *SerieFeatureDeleteOne) Exec(ctx context.Context) error {
	n, err := sfdo.sfd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{seriefeature.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sfdo *SerieFeatureDeleteOne) ExecX(ctx context.Context) {
	if err := sfdo.Exec(ctx); err != nil {
		panic(err)
	}
}
