--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5 (Debian 17.5-1.pgdg120+1)
-- Dumped by pg_dump version 17.5 (Debian 17.5-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: currencies; Type: TABLE; Schema: public; Owner: sa
--

CREATE TABLE public.currencies (
    id bigint NOT NULL,
    name character varying NOT NULL,
    symbol character varying NOT NULL,
    thousands_separator character varying NOT NULL,
    units_separator character varying NOT NULL,
    symbol_position character varying NOT NULL,
    denominator bigint NOT NULL
);


ALTER TABLE public.currencies OWNER TO sa;

--
-- Name: currencies_id_seq; Type: SEQUENCE; Schema: public; Owner: sa
--

ALTER TABLE public.currencies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.currencies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: currency_versions; Type: TABLE; Schema: public; Owner: sa
--

CREATE TABLE public.currency_versions (
    id bigint NOT NULL,
    name character varying NOT NULL,
    min_bet bigint NOT NULL,
    max_exp bigint NOT NULL,
    denominator bigint NOT NULL,
    currency_id bigint NOT NULL,
    default_multiplier bigint NOT NULL,
    deprecated boolean NOT NULL,
    crash_bet_increment bigint NOT NULL,
    slots_bet_multipliers jsonb NOT NULL,
    currencie_currency_versions bigint,
    game_type_currency_versions bigint
);


ALTER TABLE public.currency_versions OWNER TO sa;

--
-- Name: currency_versions_id_seq; Type: SEQUENCE; Schema: public; Owner: sa
--

ALTER TABLE public.currency_versions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.currency_versions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: features; Type: TABLE; Schema: public; Owner: sa
--

CREATE TABLE public.features (
    id bigint NOT NULL,
    name character varying NOT NULL,
    external_id character varying NOT NULL
);


ALTER TABLE public.features OWNER TO sa;

--
-- Name: features_id_seq; Type: SEQUENCE; Schema: public; Owner: sa
--

ALTER TABLE public.features ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.features_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: game_configs; Type: TABLE; Schema: public; Owner: sa
--

CREATE TABLE public.game_configs (
    id bigint NOT NULL,
    can_demo boolean NOT NULL,
    can_tournament boolean NOT NULL,
    can_free_bets boolean NOT NULL,
    can_drop_and_wins boolean NOT NULL,
    can_turbo boolean NOT NULL,
    is_active boolean NOT NULL,
    can_auto_bet boolean NOT NULL,
    can_auto_cashout boolean NOT NULL,
    can_ante_bet boolean NOT NULL,
    can_home_button boolean NOT NULL,
    currency_version_game_configs bigint,
    game_game_configs bigint,
    game_version_game_configs bigint,
    math_version_game_configs bigint,
    operator_game_configs bigint
);


ALTER TABLE public.game_configs OWNER TO sa;

--
-- Name: game_configs_id_seq; Type: SEQUENCE; Schema: public; Owner: sa
--

ALTER TABLE public.game_configs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.game_configs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: game_features; Type: TABLE; Schema: public; Owner: sa
--

CREATE TABLE public.game_features (
    id bigint NOT NULL,
    feature_game_features bigint,
    game_game_features bigint
);


ALTER TABLE public.game_features OWNER TO sa;

--
-- Name: game_features_id_seq; Type: SEQUENCE; Schema: public; Owner: sa
--

ALTER TABLE public.game_features ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.game_features_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: game_types; Type: TABLE; Schema: public; Owner: sa
--

CREATE TABLE public.game_types (
    id bigint NOT NULL,
    type character varying NOT NULL,
    external_type_id character varying NOT NULL
);


ALTER TABLE public.game_types OWNER TO sa;

--
-- Name: game_types_id_seq; Type: SEQUENCE; Schema: public; Owner: sa
--

ALTER TABLE public.game_types ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.game_types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: game_versions; Type: TABLE; Schema: public; Owner: sa
--

CREATE TABLE public.game_versions (
    id bigint NOT NULL,
    version character varying NOT NULL,
    can_demo boolean NOT NULL,
    can_tournament boolean NOT NULL,
    can_free_bets boolean NOT NULL,
    can_drop_and_wins boolean NOT NULL,
    can_turbo boolean NOT NULL,
    url_media_pack character varying NOT NULL,
    url_release_note character varying NOT NULL,
    deprecated boolean NOT NULL,
    available_math_versions jsonb NOT NULL,
    can_auto_bet boolean NOT NULL,
    url_game_manual character varying NOT NULL,
    can_auto_cashout boolean NOT NULL,
    can_buy_bonus boolean NOT NULL,
    can_ante_bet boolean NOT NULL,
    game_game_versions bigint,
    game_type_game_versions bigint
);


ALTER TABLE public.game_versions OWNER TO sa;

--
-- Name: game_versions_id_seq; Type: SEQUENCE; Schema: public; Owner: sa
--

ALTER TABLE public.game_versions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.game_versions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: games; Type: TABLE; Schema: public; Owner: sa
--

CREATE TABLE public.games (
    id bigint NOT NULL,
    name character varying NOT NULL,
    external_id character varying NOT NULL,
    trademark_name character varying NOT NULL,
    game_type_games bigint,
    serie_games bigint,
    studio_games bigint
);


ALTER TABLE public.games OWNER TO sa;

--
-- Name: games_id_seq; Type: SEQUENCE; Schema: public; Owner: sa
--

ALTER TABLE public.games ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.games_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: math_versions; Type: TABLE; Schema: public; Owner: sa
--

CREATE TABLE public.math_versions (
    id bigint NOT NULL,
    name character varying NOT NULL,
    version character varying NOT NULL,
    volatility bigint NOT NULL,
    rtp bigint NOT NULL,
    max_win bigint NOT NULL,
    can_buy_bonus boolean NOT NULL,
    url_release_note character varying NOT NULL,
    deprecated boolean NOT NULL,
    can_ante_bet boolean NOT NULL
);


ALTER TABLE public.math_versions OWNER TO sa;

--
-- Name: math_versions_id_seq; Type: SEQUENCE; Schema: public; Owner: sa
--

ALTER TABLE public.math_versions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.math_versions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: operators; Type: TABLE; Schema: public; Owner: sa
--

CREATE TABLE public.operators (
    id bigint NOT NULL,
    name character varying NOT NULL,
    created_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    alias character varying NOT NULL,
    platform_operator bigint
);


ALTER TABLE public.operators OWNER TO sa;

--
-- Name: operators_id_seq; Type: SEQUENCE; Schema: public; Owner: sa
--

ALTER TABLE public.operators ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.operators_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: platforms; Type: TABLE; Schema: public; Owner: sa
--

CREATE TABLE public.platforms (
    id bigint NOT NULL,
    name character varying NOT NULL,
    hash character varying NOT NULL,
    created_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    home_button_payload character varying NOT NULL
);


ALTER TABLE public.platforms OWNER TO sa;

--
-- Name: platforms_id_seq; Type: SEQUENCE; Schema: public; Owner: sa
--

ALTER TABLE public.platforms ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.platforms_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: serie_features; Type: TABLE; Schema: public; Owner: sa
--

CREATE TABLE public.serie_features (
    id bigint NOT NULL,
    feature_serie_features bigint,
    serie_serie_features bigint
);


ALTER TABLE public.serie_features OWNER TO sa;

--
-- Name: serie_features_id_seq; Type: SEQUENCE; Schema: public; Owner: sa
--

ALTER TABLE public.serie_features ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.serie_features_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: series; Type: TABLE; Schema: public; Owner: sa
--

CREATE TABLE public.series (
    id bigint NOT NULL,
    name character varying NOT NULL,
    created_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    external_id character varying NOT NULL
);


ALTER TABLE public.series OWNER TO sa;

--
-- Name: series_id_seq; Type: SEQUENCE; Schema: public; Owner: sa
--

ALTER TABLE public.series ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.series_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sessions; Type: TABLE; Schema: public; Owner: sa
--

CREATE TABLE public.sessions (
    id bigint NOT NULL,
    can_demo boolean NOT NULL,
    token character varying NOT NULL,
    client_id character varying NOT NULL,
    demo boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    currency_version_sessions bigint,
    game_sessions bigint,
    game_version_sessions bigint,
    math_version_sessions bigint,
    operator_sessions bigint
);


ALTER TABLE public.sessions OWNER TO sa;

--
-- Name: sessions_id_seq; Type: SEQUENCE; Schema: public; Owner: sa
--

ALTER TABLE public.sessions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: studios; Type: TABLE; Schema: public; Owner: sa
--

CREATE TABLE public.studios (
    id bigint NOT NULL,
    name character varying NOT NULL,
    created_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone
);


ALTER TABLE public.studios OWNER TO sa;

--
-- Name: studios_id_seq; Type: SEQUENCE; Schema: public; Owner: sa
--

ALTER TABLE public.studios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.studios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: currencies currencies_pkey; Type: CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.currencies
    ADD CONSTRAINT currencies_pkey PRIMARY KEY (id);


--
-- Name: currency_versions currency_versions_pkey; Type: CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.currency_versions
    ADD CONSTRAINT currency_versions_pkey PRIMARY KEY (id);


--
-- Name: features features_pkey; Type: CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.features
    ADD CONSTRAINT features_pkey PRIMARY KEY (id);


--
-- Name: game_configs game_configs_pkey; Type: CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.game_configs
    ADD CONSTRAINT game_configs_pkey PRIMARY KEY (id);


--
-- Name: game_features game_features_pkey; Type: CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.game_features
    ADD CONSTRAINT game_features_pkey PRIMARY KEY (id);


--
-- Name: game_types game_types_pkey; Type: CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.game_types
    ADD CONSTRAINT game_types_pkey PRIMARY KEY (id);


--
-- Name: game_versions game_versions_pkey; Type: CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.game_versions
    ADD CONSTRAINT game_versions_pkey PRIMARY KEY (id);


--
-- Name: games games_pkey; Type: CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.games
    ADD CONSTRAINT games_pkey PRIMARY KEY (id);


--
-- Name: math_versions math_versions_pkey; Type: CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.math_versions
    ADD CONSTRAINT math_versions_pkey PRIMARY KEY (id);


--
-- Name: operators operators_pkey; Type: CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.operators
    ADD CONSTRAINT operators_pkey PRIMARY KEY (id);


--
-- Name: platforms platforms_pkey; Type: CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.platforms
    ADD CONSTRAINT platforms_pkey PRIMARY KEY (id);


--
-- Name: serie_features serie_features_pkey; Type: CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.serie_features
    ADD CONSTRAINT serie_features_pkey PRIMARY KEY (id);


--
-- Name: series series_pkey; Type: CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.series
    ADD CONSTRAINT series_pkey PRIMARY KEY (id);


--
-- Name: sessions sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_pkey PRIMARY KEY (id);


--
-- Name: studios studios_pkey; Type: CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.studios
    ADD CONSTRAINT studios_pkey PRIMARY KEY (id);


--
-- Name: currency_versions currency_versions_currencies_currency_versions; Type: FK CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.currency_versions
    ADD CONSTRAINT currency_versions_currencies_currency_versions FOREIGN KEY (currencie_currency_versions) REFERENCES public.currencies(id) ON DELETE SET NULL;


--
-- Name: currency_versions currency_versions_game_types_currency_versions; Type: FK CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.currency_versions
    ADD CONSTRAINT currency_versions_game_types_currency_versions FOREIGN KEY (game_type_currency_versions) REFERENCES public.game_types(id) ON DELETE SET NULL;


--
-- Name: game_configs game_configs_currency_versions_game_configs; Type: FK CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.game_configs
    ADD CONSTRAINT game_configs_currency_versions_game_configs FOREIGN KEY (currency_version_game_configs) REFERENCES public.currency_versions(id) ON DELETE SET NULL;


--
-- Name: game_configs game_configs_game_versions_game_configs; Type: FK CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.game_configs
    ADD CONSTRAINT game_configs_game_versions_game_configs FOREIGN KEY (game_version_game_configs) REFERENCES public.game_versions(id) ON DELETE SET NULL;


--
-- Name: game_configs game_configs_games_game_configs; Type: FK CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.game_configs
    ADD CONSTRAINT game_configs_games_game_configs FOREIGN KEY (game_game_configs) REFERENCES public.games(id) ON DELETE SET NULL;


--
-- Name: game_configs game_configs_math_versions_game_configs; Type: FK CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.game_configs
    ADD CONSTRAINT game_configs_math_versions_game_configs FOREIGN KEY (math_version_game_configs) REFERENCES public.math_versions(id) ON DELETE SET NULL;


--
-- Name: game_configs game_configs_operators_game_configs; Type: FK CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.game_configs
    ADD CONSTRAINT game_configs_operators_game_configs FOREIGN KEY (operator_game_configs) REFERENCES public.operators(id) ON DELETE SET NULL;


--
-- Name: game_features game_features_features_game_features; Type: FK CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.game_features
    ADD CONSTRAINT game_features_features_game_features FOREIGN KEY (feature_game_features) REFERENCES public.features(id) ON DELETE SET NULL;


--
-- Name: game_features game_features_games_game_features; Type: FK CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.game_features
    ADD CONSTRAINT game_features_games_game_features FOREIGN KEY (game_game_features) REFERENCES public.games(id) ON DELETE SET NULL;


--
-- Name: game_versions game_versions_game_types_game_versions; Type: FK CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.game_versions
    ADD CONSTRAINT game_versions_game_types_game_versions FOREIGN KEY (game_type_game_versions) REFERENCES public.game_types(id) ON DELETE SET NULL;


--
-- Name: game_versions game_versions_games_game_versions; Type: FK CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.game_versions
    ADD CONSTRAINT game_versions_games_game_versions FOREIGN KEY (game_game_versions) REFERENCES public.games(id) ON DELETE SET NULL;


--
-- Name: games games_game_types_games; Type: FK CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.games
    ADD CONSTRAINT games_game_types_games FOREIGN KEY (game_type_games) REFERENCES public.game_types(id) ON DELETE SET NULL;


--
-- Name: games games_series_games; Type: FK CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.games
    ADD CONSTRAINT games_series_games FOREIGN KEY (serie_games) REFERENCES public.series(id) ON DELETE SET NULL;


--
-- Name: games games_studios_games; Type: FK CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.games
    ADD CONSTRAINT games_studios_games FOREIGN KEY (studio_games) REFERENCES public.studios(id) ON DELETE SET NULL;


--
-- Name: operators operators_platforms_Operator; Type: FK CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.operators
    ADD CONSTRAINT "operators_platforms_Operator" FOREIGN KEY (platform_operator) REFERENCES public.platforms(id) ON DELETE SET NULL;


--
-- Name: serie_features serie_features_features_serie_features; Type: FK CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.serie_features
    ADD CONSTRAINT serie_features_features_serie_features FOREIGN KEY (feature_serie_features) REFERENCES public.features(id) ON DELETE SET NULL;


--
-- Name: serie_features serie_features_series_serie_features; Type: FK CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.serie_features
    ADD CONSTRAINT serie_features_series_serie_features FOREIGN KEY (serie_serie_features) REFERENCES public.series(id) ON DELETE SET NULL;


--
-- Name: sessions sessions_currency_versions_sessions; Type: FK CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_currency_versions_sessions FOREIGN KEY (currency_version_sessions) REFERENCES public.currency_versions(id) ON DELETE SET NULL;


--
-- Name: sessions sessions_game_versions_sessions; Type: FK CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_game_versions_sessions FOREIGN KEY (game_version_sessions) REFERENCES public.game_versions(id) ON DELETE SET NULL;


--
-- Name: sessions sessions_games_sessions; Type: FK CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_games_sessions FOREIGN KEY (game_sessions) REFERENCES public.games(id) ON DELETE SET NULL;


--
-- Name: sessions sessions_math_versions_sessions; Type: FK CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_math_versions_sessions FOREIGN KEY (math_version_sessions) REFERENCES public.math_versions(id) ON DELETE SET NULL;


--
-- Name: sessions sessions_operators_sessions; Type: FK CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_operators_sessions FOREIGN KEY (operator_sessions) REFERENCES public.operators(id) ON DELETE SET NULL;


--
-- PostgreSQL database dump complete
--

